# Generated by Django 3.2.5 on 2021-10-30 08:10

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(default='chennai', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='id_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_rename, verbose_name='ID Picture'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='institution',
            field=models.CharField(default='SSNCE', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_rename1, verbose_name='Profile Picture'),
        ),
    ]
