# Generated by Django 3.2.5 on 2021-10-30 08:11

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20211030_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_rename1, verbose_name='ID Picture'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
